export const ENDPOINT = "https://graph.instagram.com/";
export const TOKEN =
  "IGQVJVbUtFZAzNRYlZA1MUlaNGFid3NWRTBHY2FRc1ljOGZAzMlFpWTlpZAGpUa2RMU2ZA4LXNTZAE85WkhKaDVUMFdnOVY4bnlGZATAzem42YmNJLS14NjdUX3NETU5EZAy1OenloczJ1TjhWdU00TUF6dDBIYwZDZD";
